// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `HelloWorld.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package firstHelloWorld;

public interface HelloWorldPrx extends Ice.ObjectPrx
{
    public void greeting(String value);

    public void greeting(String value, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_greeting(String value);

    public Ice.AsyncResult begin_greeting(String value, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_greeting(String value, Ice.Callback __cb);

    public Ice.AsyncResult begin_greeting(String value, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_greeting(String value, Callback_HelloWorld_greeting __cb);

    public Ice.AsyncResult begin_greeting(String value, java.util.Map<String, String> __ctx, Callback_HelloWorld_greeting __cb);

    public Ice.AsyncResult begin_greeting(String value, 
                                          IceInternal.Functional_VoidCallback __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_greeting(String value, 
                                          IceInternal.Functional_VoidCallback __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                          IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_greeting(String value, 
                                          java.util.Map<String, String> __ctx, 
                                          IceInternal.Functional_VoidCallback __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_greeting(String value, 
                                          java.util.Map<String, String> __ctx, 
                                          IceInternal.Functional_VoidCallback __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                          IceInternal.Functional_BoolCallback __sentCb);

    public void end_greeting(Ice.AsyncResult __result);

    public void testAnotherOperation(String value);

    public void testAnotherOperation(String value, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_testAnotherOperation(String value);

    public Ice.AsyncResult begin_testAnotherOperation(String value, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_testAnotherOperation(String value, Ice.Callback __cb);

    public Ice.AsyncResult begin_testAnotherOperation(String value, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_testAnotherOperation(String value, Callback_HelloWorld_testAnotherOperation __cb);

    public Ice.AsyncResult begin_testAnotherOperation(String value, java.util.Map<String, String> __ctx, Callback_HelloWorld_testAnotherOperation __cb);

    public Ice.AsyncResult begin_testAnotherOperation(String value, 
                                                      IceInternal.Functional_VoidCallback __responseCb, 
                                                      IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_testAnotherOperation(String value, 
                                                      IceInternal.Functional_VoidCallback __responseCb, 
                                                      IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                      IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_testAnotherOperation(String value, 
                                                      java.util.Map<String, String> __ctx, 
                                                      IceInternal.Functional_VoidCallback __responseCb, 
                                                      IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_testAnotherOperation(String value, 
                                                      java.util.Map<String, String> __ctx, 
                                                      IceInternal.Functional_VoidCallback __responseCb, 
                                                      IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                      IceInternal.Functional_BoolCallback __sentCb);

    public void end_testAnotherOperation(Ice.AsyncResult __result);
}
