// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `HelloWorld.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package firstHelloWorld;

public interface HelloWorld extends Ice.Object,
                                    _HelloWorldOperations, _HelloWorldOperationsNC
{
    public static final String ice_staticId = "::firstHelloWorld::HelloWorld";

    public static final long serialVersionUID = 7804851355762739783L;
}
